# nixpacks.toml

[phases.setup]
# Add required system packages for WeasyPrint and general build tools
aptPkgs = [
    "build-essential",
    "python3-dev",
    "libcairo2",
    "libpango-1.0-0",
    "libpangocairo-1.0-0",
    "libgdk-pixbuf2.0-0",
    "libffi-dev",
    "shared-mime-info",
    "libgobject-2.0-0",
    "python3-cffi"
]