# nixpacks.toml

[phases.setup]
# Add required system packages for WeasyPrint based on official documentation
aptPkgs = [
    "libcairo2",
    "libpango-1.0-0",
    "libpangocairo-1.0-0",
    "libgdk-pixbuf2.0-0",
    "libffi-dev",
    "shared-mime-info",
    "libgobject-2.0-0"
]
