# nixpacks.toml

[phases.setup]
aptPkgs = [
    "python3-weasyprint",
    "python3-pip",
    "python3-dev"
]

[variables]
LD_LIBRARY_PATH = "/usr/lib/x86_64-linux-gnu:/usr/lib"
PKG_CONFIG_PATH = "/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/share/pkgconfig"