"""Add performance indexes for user_id and date columns

Revision ID: 1d01d06679e8
Revises: 033faf89f4e5
Create Date: 2025-07-11 16:25:49.435286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d01d06679e8'
down_revision = '033faf89f4e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add indexes for frequently queried user_id foreign keys
    # Note: Using actual table names that exist in database
    op.create_index('idx_diary_entry_user_id', 'diary_entry', ['user_id'])
    op.create_index('idx_daily_stats_user_id', 'daily_stats', ['user_id'])
    op.create_index('idx_goals_user_id', 'goals', ['user_id'])
    
    # Add indexes for date columns used in queries
    op.create_index('idx_diary_entry_entry_date', 'diary_entry', ['entry_date'])
    op.create_index('idx_daily_stats_date', 'daily_stats', ['date'])
    op.create_index('idx_goals_week_start', 'goals', ['week_start'])
    op.create_index('idx_goals_week_end', 'goals', ['week_end'])
    
    # Add composite indexes for common query patterns
    op.create_index('idx_diary_entry_user_date', 'diary_entry', ['user_id', 'entry_date'])
    op.create_index('idx_daily_stats_user_date', 'daily_stats', ['user_id', 'date'])
    op.create_index('idx_goals_user_status', 'goals', ['user_id', 'status'])
    
    # Add index for diary entry rating (used in filtering)
    op.create_index('idx_diary_entry_rating', 'diary_entry', ['rating'])
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop indexes in reverse order
    op.drop_index('idx_diary_entry_rating', table_name='diary_entry')
    op.drop_index('idx_goals_user_status', table_name='goals')
    op.drop_index('idx_daily_stats_user_date', table_name='daily_stats')
    op.drop_index('idx_diary_entry_user_date', table_name='diary_entry')
    op.drop_index('idx_goals_week_end', table_name='goals')
    op.drop_index('idx_goals_week_start', table_name='goals')
    op.drop_index('idx_daily_stats_date', table_name='daily_stats')
    op.drop_index('idx_diary_entry_entry_date', table_name='diary_entry')
    op.drop_index('idx_goals_user_id', table_name='goals')
    op.drop_index('idx_daily_stats_user_id', table_name='daily_stats')
    op.drop_index('idx_diary_entry_user_id', table_name='diary_entry')
    
    # ### end Alembic commands ###
